# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install \
            poetry \
            flake8 \
            isort \
            pytest \
            pytest-asyncio \
            flake8-bugbear \
            flake8-comprehensions \
            flake8-docstrings \
            flake8-eradicate \
            flake8-isort \
            pep8-naming \
            flake8-string-format \
            flake8-bandit \
            flake8-builtins \
            flake8-black \
            flake8-expression-complexity \
            flake8-annotations-complexity \
            flake8-requirements
          poetry install
      - name: Check flake8
        run: |
          flake8 . --count --show-source --statistics --exit-zero
      - name: Check isort
        run: |
          isort **/*.py --check-only --verbose
      - name: Test with pytest
        run: |
          pytest
